// Auto-generated types from AgentMark
// Do not edit this file directly

interface AnimalDrawingIn { [key: string]: any }

type AnimalDrawingOut = string

interface CustomerSupportAgentIn {
  /**
   * The customer's question
   */
  customer_question: string;
}


type CustomerSupportAgentOut = string

interface PartyPlannerIn {
  /**
   * A block of text describing the upcoming party and attendees.
   */
  party_text: string;
}


interface PartyPlannerOut {
  /**
   * List of names of people attending the party.
   */
  names: string[];
}


interface StoryTellerIn { [key: string]: any }

type StoryTellerOut = string

type AnimalDrawing = {
  kind: 'image';
  input:  AnimalDrawingIn;
  output: AnimalDrawingOut;
};

interface SearchKnowledgebaseArgs {
  /**
   * The search query to find relevant information
   */
  query: string;
}


export interface Tools {
  search_knowledgebase: { args: SearchKnowledgebaseArgs };
}

type CustomerSupportAgent = {
  kind: 'text';
  input:  CustomerSupportAgentIn;
  output: CustomerSupportAgentOut;
  tools?: Array<keyof Tools>;
};

type PartyPlanner = {
  kind: 'object';
  input:  PartyPlannerIn;
  output: PartyPlannerOut;
};

type StoryTeller = {
  kind: 'text';
  input:  StoryTellerIn;
  output: StoryTellerOut;
};

export default interface AgentmarkTypes {
  "animal-drawing.prompt.mdx": AnimalDrawing,
  "customer-support-agent.prompt.mdx": CustomerSupportAgent,
  "party-planner.prompt.mdx": PartyPlanner,
  "story-teller.prompt.mdx": StoryTeller
}
